name: TEclass2
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python=3.10.9
  - biopython
  - matplotlib==3.5.1
  - numpy==1.22.3
  - pandas==1.4.2
  - PyYAML==6.0
  - scikit-learn==1.0.2
  - scipy==1.8.0
  - tokenizers==0.11.6
  - pytorch==1.12.1
  - torchvision==0.12.0
  - tqdm==4.63.0
  - transformers==4.17.0
  - tensorboardX==2.5
  - openssl
  - yaml
